title: Riyas Mohammed # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 UI Dev Manager
  <br><br>
  <a href="mailto:aashima.ahuja811@gmail.com">maddy261@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/riyas-mohammed-233723129">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/Riyas-M">Gihub</a> 
theme: jekyll-theme-minimal
